CHANGELOG.md
NotifyTests/IntegrationTests/NotificationIntegrationClientTests.cs
src/Notify/Properties/AssemblyInfo.cs

This adds support for letter templates that are now included in our integration tests pipeline.
Version bump to `1.3.0`.

Add support for letter templates in the integration tests

---

CHANGELOG.md
NotifyTests/IntegrationTests/NotificationIntegrationClientTests.cs
README.md
src/Notify/Models/Responses/TemplatePreviewResponse.cs
src/Notify/Models/Responses/TemplateResponse.cs
src/Notify/Properties/AssemblyInfo.cs

The public api has a pull request to include the name in template responses, this pull request adds the name property to the template response models so the new data is used.
Also, ignore the duplicate commit reference earlier, I hadn't set the email config on this machine... 🙂

Add template name to template response models

---

CHANGELOG.md
src/Notify/Client/NotificationClient.cs
src/Notify/Properties/AssemblyInfo.cs

This ensures the personalisation cannot be null when calling `SendLetter`.

Make personalisation nonnull when sending letters

---

.github/PULL_REQUEST_TEMPLATE.md
src/Notify/Properties/AssemblyInfo.cs

We should clarify what our expectations are of external developers contributing to our codebase.
A good way to do this is through a pull request template, which lets developers check off what they’ve done. A lot of the GOV.UK frontend repos do this, eg
https://github.com/alphagov/govuk_elements/blob/3c5c43a6fd4209cf2b6d180e7a5eadf6fa94c132/.github/PULL_REQUEST_TEMPLATE.md
This commit also documents how we do version numbering, so that an external developer would have a reasonable chance of being able to increment the version number in the right way.

Add a pull request template

---

CHANGELOG.md
src/Notify/Notify.nuspec
src/Notify/Properties/AssemblyInfo.cs

Needed to pin the dependencies as when trying to upgrade the packages to the latest versions the libraries do not work with .Net framework.

Pin dependencies to prevent problems during upgrades

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
Makefile
NotifyTests/IntegrationTests/Assertions.cs
NotifyTests/IntegrationTests/NotificationIntegrationClientTests.cs
NotifyTests/NotifyTests.csproj
NotifyTests/UnitTests/Constants.cs
NotifyTests/UnitTests/NotificationUnitClientTests.cs
NotifyTests/packages.config
README.md
src/Notify/Authentication/Authenticator.cs
src/Notify/Client/BaseClient.cs
src/Notify/Client/NotificationClient.cs
src/Notify/Models/Link.cs
src/Notify/Models/NotificationList.cs
src/Notify/Models/Responses/Link.cs
src/Notify/Models/Responses/ReceivedTextListResponse.cs
src/Notify/Models/Responses/ReceivedTextResponse.cs
src/Notify/Notify.csproj
src/Notify/Properties/AssemblyInfo.cs
src/Notify/packages.config

Added extra functionality in this client to 
- Pin dependencies to versions so that this will work with .Net framework 4.6.2 and 4.7.
- Allow sending of sms from an sms_sender by passing in the optional `sms_sender_id`.
- Extra function to get all received texts `GetReceivedTexts`, response is paged with a size of 250.
- Added a `Makefile` to make it easier for non Visual Studio developers to build, test and package the client.

Add get received texts, sms_sender option and a Makefile

---

NotifyTests/IntegrationTests/NotificationIntegrationClientTests.cs

previously templates table has \n but no \r, we now read from templates_history which has \r\n, so should update test. templates table should also really have \r as well.

Make integration tests expect \r in template content

---

Makefile

Comments were confusing in the `Makefile`, so corrected and improved styling

Fixed styling and descriptions in comments

---

appveyor.txt

Use master appveyor config rather than the migrate-to-dotnet-core branch as changes to the appveyor config file have been merged.

Use master branch for appveyor config

---

src/Notify.Tests/IntegrationTests/Assertions.cs

When a letter is created with a test api key the status of the notification is set to received.

Update the integration test to look for the right status

---

README.md

Doug, from HO, has updated README to add guidance for including the Notify package from bintray in CI tooling, such as that provided through the HO ACP

Add reference to nuget.config to readme.md

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
src/Notify.Tests/IntegrationTests/Assertions.cs
src/Notify/Notify.csproj

Occasional failures of the integration test due to new virus states which will block deployment so these have been added in: `pending-virus-check` and `virus-scan-failed`

Add new noti statuses

---

src/Notify.Tests/IntegrationTests/NotificationIntegrationClientTests.cs

We’ve changed from \r\n to \n to fix a bug where double linebreaks were getting sent.

Fix newlines in texts message responses

---

CHANGELOG.md
DOCUMENTATION.md
README.md
src/Notify/Notify.csproj

Bumped the version and updated the documentation since the Notification class now has an additional property, `createdByName`.
[Pivotal story](https://www.pivotaltracker.com/story/show/158970584)

Bump version from 2.0.1 to 2.1.0

---

src/Notify/Client/NotificationClient.cs
src/Notify/Interfaces/INotificationClient.cs
src/Notify/Notify.csproj

The NotificationClient did not implement the INotificationClient interface. Being unable to use an interface in the place of the NotificationClient makes unit testing rather painful, as we have to instead mock the IHttpClient.
**I dont feel this is applicable as no functional code has changed**
**I am unsure if any doccumentation would need to change as the usage of the NotificationClient is unchanged**

Implement interface

---

DOCUMENTATION.md

Documentation was incorrect. Looks like it was copied from the text message section.

Fix wrong method name in send email example

---

CHANGELOG.md
src/Notify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
src/Notify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
src/Notify.Tests/UnitTests/NotificationClientAsyncUnitTests.cs
src/Notify.Tests/UnitTests/NotificationClientUnitTests.cs
src/Notify/Client/BaseClient.cs
src/Notify/Client/HttpClientWrapper.cs
src/Notify/Client/NotificationClient.cs
src/Notify/Interfaces/IAsyncNotificationClient.cs
src/Notify/Interfaces/IBaseClient.cs
src/Notify/Interfaces/IHttpClient.cs
src/Notify/Interfaces/INotificationClient.cs
src/Notify/Notify.csproj

The current implementation of the API Client is synchronous.  This was causing bottlenecks during our load testing (which sends lots of messages using Notify).  We modified the code to make the API Client methods asynchronous as part of measures to improve the performance of our system.  We would like to share these changes with you, as they may be useful for other projects.
I have updated CHANGELOG.md but not DOCUMENTATION.md.  Should I duplicate all the descriptions of the synchronous methods to describe their asynchronous counterparts?  Or is it better to add a footnote to say that asynchronous versions of the methods are available?

Implemented asynchronous version of Notify API

---

DOCUMENTATION.md

Add a code snippet to illustrated that .NET users can create a NotificationClient with their own proxied HttpClient

Update docs to include proxy example

---

DOCUMENTATION.md

The documentation needed an update for the responses.

Correct the documentation describing the responses.

---

DOCUMENTATION.md

Uses the warning pattern from here:
https://github.com/alphagov/tech-docs-gem/commit/b650d313b893af4990603c1cff917ab1776a0d65

Add warning about version 2.5.0

---

DOCUMENTATION.md

This PR changes the wording of 2 message status descriptions:
- mentioning the 72 hour period in the _Sending_ status makes it explicit that this a message that remains in this state for longer than a users expects is not 'stuck'
- not mentioning the 72 hour period in the _Phone not accepting messages right now_ status should reduce any confusion for users who see this status after <72 hours
This change was prompted by feedback from a user on x-gov Slack:
>We sent out a message last night and there were a few numbers that did not get it, on checking one, it gives the message: _"The provider could not deliver the message after trying for 72 hours. This can happen when the recipient’s phone is off..."_ Given it is not even 24 hours after the text was sent, any ideas why this report is …

Update status descriptions to help users understand the 72 hour period (.net)

---

CHANGELOG.md
DOCUMENTATION.md
src/Notify.Tests/UnitTests/NotificationClientAsyncUnitTests.cs
src/Notify.Tests/UnitTests/NotificationClientUnitTests.cs
src/Notify/Client/NotificationClient.cs
src/Notify/Notify.csproj

Equivalent functionality to Equivalent functionality as https://github.com/alphagov/notifications-python-client/pull/165

Allow CSV files sent by email and doc download to download as .CSV

---

CHANGELOG.md
src/Notify/Authentication/Authenticator.cs
src/Notify/Notify.csproj

There have been two major releases since the version we were using. From
version `6.0.0` onwards the `JwtDecoder` takes a fourth argument, the
algorithm. There are no changes to how the code works, but we do need to
pass that argument in.
I've tested this change against the integration tests and it works with
versions 6.x and 7.x of JWT, so have let people use either instead of
pinning too precisely.

Update JWT to a later version

---

CHANGELOG.md
src/Notify/Authentication/Authenticator.cs
src/Notify/Notify.csproj

This fixes the issue introduced in version 3.0.0. Version 3.0.0 allowed
the JWT dependency to be version 6.x or 7.x, however version 7.0
introduced a breaking change which meant that the project would not
compile.
TODO: look at why the integration tests did appear to pass with version
7.x before.

Fix compile error by pinning JWT more precisely

---

Dockerfile

We were using 2.1 of .NET core but this is not end of life.
You can see on https://hub.docker.com/_/microsoft-dotnet-sdk that
3.1 is long term support.
Also note, that the repo name has changed as per
https://github.com/dotnet/dotnet-docker/issues/2375.
Also note, I could have upgraded us to 5.1 but I went for 3.1 for two
reasons
- it's a smaller change
- good to know that we support the oldest .net stuff so we don't add
anything in that is only supported by newer versions
However, I could be easily persuaded to choose 5.1 instead.

Upgrade dockerfile used for tests

---

Dockerfile

In #138 I
thought that 2.1 was no longer supported. This was incorrect. It is
supported until the end of August as per
https://dotnet.microsoft.com/platform/support/policy/dotnet-core
This, combined with the fact that actually if you run `make
test-with-docker` you will see that the change I added was broken and
the tests fail in docker.
Therefore by downgrading we support the lowest version possible and our
tests are fixed in docker. Win, Win.

Downgrade docker image

---

appveyor.txt

appveyor pull the appveyor.txt file from master, which contains instructions on how to test the code. Since https://github.com/alphagov/notifications-net-client/pull/141 changes the path of the tests csproj, we need master to look there first before appveyor will be able to test it.

make appveyor.txt point to new test source

---

DOCUMENTATION.md

Uses the correct comment symbol, and adds a missing semi-colon, and fixes the style of quotes so that the docs don't look like this anymore:

Minor formatting fixes

---

DOCUMENTATION.md

In most places we were saying that the client returns "a `Notify.Exceptions.NotifyClientException` and an error code". It was pointed out by a user that all the details returned when there is an exception are actually in the exception message, so the docs were a little unclear.
We already had one place where we the docs talked about the exception "containing the relevant error code", so this uses that phrasing everywhere.
It also changes the headings of the error table to be consistent, and fixes a couple of places where we wrongly said the error that was returned was an `HTTPError`.
[Pivotal story](https://www.pivotaltracker.com/story/show/166607638)

Update description of `Notify.Exceptions.NotifyClientException` in docs

---

appveyor.txt
publish.cmd

https://www.pivotaltracker.com/story/show/181753597
This fixes a bug in the publish.cmd script and updates the (encrypted)
API key we use for Nuget as the old one had expired.
See the commit messages for more details.

Fix release pipeline

---

CHANGELOG.md
Dockerfile
Makefile
appveyor.txt
src/GovukNotify.Tests/GovukNotify.Tests.csproj
src/GovukNotify/GovukNotify.csproj

https://www.pivotaltracker.com/story/show/181753597
This moves us from the old world of .NET Core and .NET Standard to the
new, unifired ".NET". See the first commit for more details.
I've also added another commit to loosen some of the dependency upper
version limits - these are still useful but were out-of-date.
Like [^1] this is a major change in the sense that anyone still working
on projects in older, unsupported incarnations of .NET will have to pin
and older version of this package and won't get future updates.
Due to the change in appveyor.txt this needs to be tested by manually 
overriding the reference to it in Appveyor - same as in [^1].
[^1]: https://github.com/alphagov/notifications-net-client/pull/156

Bump target .NET (Core) version to 6

---

CHANGELOG.md
DOCUMENTATION.md
src/GovukNotify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
src/GovukNotify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
src/GovukNotify.Tests/UnitTests/NotificationClientAsyncUnitTests.cs
src/GovukNotify.Tests/UnitTests/NotificationClientUnitTests.cs
src/GovukNotify/Client/NotificationClient.cs
src/GovukNotify/GovukNotify.csproj

Update client for the new document download feature which allows specifying a download filename for files sent by email.
This supercedes the old `isCsv` parameter that was inconsistent at best.
Given this, we are dropping support for `isCsv` altogether.

Allow setting custom filenames for documents

---

appveyor.txt

This expires automatically every 365 days. Corresponding update in `notifications-credentials`.
When updating this value, encrypt the value at
https://ci.appveyor.com/tools/encrypt before adding it to that file.

Update the API Key for nuget/appveyor.

---

CHANGELOG.md
src/GovukNotify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
src/GovukNotify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
src/GovukNotify.Tests/UnitTests/Constants.cs
src/GovukNotify/GovukNotify.csproj
src/GovukNotify/Models/CostDetails.cs
src/GovukNotify/Models/Notification.cs

New fields have been added to the response of `get_notification(notificationId)` endpoint
- cost_in_pounds
- is_cost_data_ready
- cost_details:
-- **Nested fields for letters**:
--- billable_sheets_of_paper
--- postage
-- **Nested fields for sms**:
--- billable_sms_fragments
--- international_rate_multiplier
--- sms_rate
Based on the addition this PR updates our client documentation to showcase an aligned response for the endpoint
[3. Add GET notification cost data to API clients and API client docs](https://trello.com/c/5VZrBNpU/845-3-add-get-notification-cost-data-to-api-clients-and-api-client-docs)

chore: include new notification fields (cost_in_pounds, is_data_ready and cost_details)
