- CHANGELOG.md
- README.md
- src/Notify/Client/NotificationClient.cs
- src/Notify/Models/Notification.cs
- src/Notify/Properties/AssemblyInfo.cs
- test/NotifyIntegrationTests/NotificationClientTests.cs
This adds the ability to `GetNotifications` with a `reference` or `olderThanId`. 
The tests have been updated based on changes made in the notifications-api along with the README.
A CHANGELOG has been added with release notes.
> Add minor updates for v2

- appveyor.txt
Added encrypted letter template id
> Add letter template id

- README.md
- updated error messages 
- update options available for getting all templates types to include letters
> Update error message in line with other client docs

- src/Notify/Properties/AssemblyInfo.cs
- Updated the assembly info version to match the new version of the
client so that nuget packages build with the correct version.
> Update Assembly Info

- appveyor.txt
- this needs to be added to the master branch before creating any PRs
Not applicable as just adding env vars -
> Add encrypted values for inbound_sms, api sending keys, and sms_sender

- README.md
Heading for getting received text messages should be `Get all received text messages` rather than `Send messages`
> Update heading in README

- src/Notify.Tests/UnitTests/Constants.cs
- src/Notify/Models/Notification.cs
The createdByName now gets returned from the API, so the Notification model can be updated to also show this value.
> Add createdByName to Notification model

- DOCUMENTATION.md
- [N/A] I’ve written unit tests for these changes
- [N/A] I’ve bumped the version number (in `src/Notify/Notify.csproj`)
> Add information about using a proxy to the documentation

- README.md
- [ n/a] I’ve written unit tests for these changes
- [n/a] I’ve bumped the version number (in `src/Notify/Notify.csproj`)
> Add proxy info to the README

- README.md
Fixes instrictions on how to install via Nuget (#55)
(I don't think the two unchecked items need doing as it's just a documentation change)
> Update Nuget instructions in docs

- src/Notify.Tests/IntegrationTests/Assertions.cs
Add validation-failed to test assertions
> Add validation-failed to test assertions

- CONTRIBUTING.md
- DOCUMENTATION.md
> Fix typo in docs

- DOCUMENTATION.md
Adds content so headings don't skip levels. This is to pass the accessibility requirements.
> Add content so headings do not skip levels

- CHANGELOG.md
- DOCUMENTATION.md
- src/Notify.Tests/IntegrationTests/NotificationIntegrationClientTests.cs
- src/Notify.Tests/UnitTests/Constants.cs
- src/Notify.Tests/UnitTests/NotificationUnitClientTests.cs
- src/Notify/Client/NotificationClient.cs
- src/Notify/Models/Notification.cs
- src/Notify/Models/Responses/LetterNotificationResponse.cs
- src/Notify/Models/Responses/NotificationResponse.cs
- src/Notify/Notify.csproj
Also add postage to Notification
> Add postage argument to send precompiled letter request

- CHANGELOG.md
- src/Notify/Notify.csproj
> Update jwt version

- CHANGELOG.md
> Fix changelog version numbers

- DOCUMENTATION.md
> Docs tweaks

- CHANGELOG.md
- src/Notify/Client/BaseClient.cs
- src/Notify/Client/HttpClientWrapper.cs
- src/Notify/Client/NotificationClient.cs
- src/Notify/Notify.csproj
Many thanks to @david-preston-triad for his PR that this is rebased from (https://github.com/alphagov/notifications-net-client/pull/101)
> David preston triad fix sync api

- DOCUMENTATION.md
> Fix the link.

- CHANGELOG.md
- DOCUMENTATION.md
- src/Notify.Tests/UnitTests/NotificationClientUnitTests.cs
- src/Notify/Client/NotificationClient.cs
- src/Notify/Interfaces/IAsyncNotificationClient.cs
- src/Notify/Interfaces/INotificationClient.cs
- src/Notify/Notify.csproj
Add param `includeSpreadsheetUploads` to `GetNotifications`
>  Add param `includeSpreadsheetUploads` to `GetNotifications`

- CHANGELOG.md
- DOCUMENTATION.md
- src/Notify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
- src/Notify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
- src/Notify.Tests/UnitTests/NotificationClientAsyncUnitTests.cs
- src/Notify.Tests/UnitTests/NotificationClientUnitTests.cs
- src/Notify/Client/BaseClient.cs
- src/Notify/Client/NotificationClient.cs
- src/Notify/Notify.csproj
> Get Pdf for letter

- CHANGELOG.md
- DOCUMENTATION.md
- src/Notify/Client/NotificationClient.cs
> file, not doc

- CHANGELOG.md
- DOCUMENTATION.md
- src/Notify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
- src/Notify/Models/Responses/TemplateResponse.cs
- src/Notify/Notify.csproj
story ticket: https://www.pivotaltracker.com/story/show/173511626
> Add letter_contact_block to Template response

- DOCUMENTATION.md
Small change to docs to make consistent with the other clients.
> All the other doc use Upload your file, changed for consistency.

- DOCUMENTATION.md
See https://github.com/alphagov/notifications-python-client/pull/195
> Add retention period for doc download

- Dockerfile
https://www.pivotaltracker.com/story/show/181753597
This replaces [^1].
[^1]: https://github.com/alphagov/notifications-aws/pull/1072/files#diff-11e3d2a469de5db25f0f6a317d8f32224549a1172059de4455ff50ff19edb919R299
> Install "jq" dependency here instead of in CI

- CHANGELOG.md
- Makefile
- src/GovukNotify.Tests/IntegrationTests/Assertions.cs
- src/GovukNotify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
- src/GovukNotify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
- src/GovukNotify.Tests/UnitTests/AuthenticatorTests.cs
- src/GovukNotify.Tests/UnitTests/Constants.cs
- src/GovukNotify.Tests/UnitTests/NotificationClientAsyncUnitTests.cs
- src/GovukNotify.Tests/UnitTests/NotificationClientUnitTests.cs
- src/GovukNotify/Authentication/Authenticator.cs
- src/GovukNotify/Client/BaseClient.cs
- src/GovukNotify/Client/NotificationClient.cs
- src/GovukNotify/GovukNotify.csproj
- src/GovukNotify/Interfaces/IAsyncNotificationClient.cs
- src/GovukNotify/Interfaces/IBaseClient.cs
- src/GovukNotify/Interfaces/IHttpClient.cs
- src/GovukNotify/Interfaces/INotificationClient.cs
- src/GovukNotify/Models/Notification.cs
- src/GovukNotify/Models/NotifyHTTPError.cs
- src/GovukNotify/Models/Responses/EmailNotificationResponse.cs
- src/GovukNotify/Models/Responses/NotifyHTTPErrorResponse.cs
Definitely review commit by commit. This is the equivalent of https://github.com/alphagov/notifications-python-client/pull/241 but I've added some other commits that tidy up the tests and do a bunch of minor formatting changes.
> Unsubscribe link

- Dockerfile
- src/GovukNotify.Tests/IntegrationTests/NotificationClientAsyncIntegrationTests.cs
- src/GovukNotify.Tests/IntegrationTests/NotificationClientIntegrationTests.cs
[Trello card](https://trello.com/c/D1m5uleD/952-run-api-client-integration-tests-as-part-of-new-pipeline)
Some small updates to make the integration tests runnable in the dev environments via the new deploy pipeline.
[Tested in dev-a](https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/162) (5 times in a row to check for flakiness)
> Make the integration tests compatible with the dev environments
